
package org.tut.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Sep 03 21:29:08 PDT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getUsersResponse", namespace = "http://service.tut.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUsersResponse", namespace = "http://service.tut.org/")

public class GetUsersResponse {

    @XmlElement(name = "return")
    private java.util.List<org.tut.model.User> _return;

    public java.util.List<org.tut.model.User> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<org.tut.model.User> new_return)  {
        this._return = new_return;
    }

}

