
package org.tut.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Sep 03 21:29:08 PDT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "setEuResponse", namespace = "http://service.tut.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setEuResponse", namespace = "http://service.tut.org/")

public class SetEuResponse {


}

